### ISSUE TITLE
1.4. Creación historia de usuario

### ISSUE THREAD

**Issue by lutriana** [ISCOUTB/AH-TaskManager#4]

**Comment by lutriana** [comment]
[Registro de Cambios de Requerimientos a Historias de Usuario y Tareas.pdf](https://github.com/user-attachments/files/17013558/Registro.de.Cambios.de.Requerimientos.a.Historias.de.Usuario.y.Tareas.pdf)

**Comment by sajkcaz19** [comment]
[Registro de Cambios de Requerimientos a Historias de Usuario y Tareas.pdf](https://github.com/user-attachments/files/17013569/Registro.de.Cambios.de.Requerimientos.a.Historias.de.Usuario.y.Tareas.pdf)
