### ISSUE TITLE
1.7 Mockup

### ISSUE THREAD

**Issue by sajkcaz19** [ISCOUTB/AH-TaskManager#7]

**Comment by sajkcaz19** [comment]
**PROTOTIPO MOVIL: USUARIO**
[Prototipo para móvil panel de usuario V.1.pdf](https://github.com/user-attachments/files/17013367/Prototipo.para.movil.panel.de.usuario.V.1.pdf)

**PROTOTIPO MOVIL: PRINCIPAL**
_Por definir_

**PROTOTIPO MOVIL: UBICACION DE ARCHIVOS**
_Por definir_

**PROTOTIPO MOVIL: NOTIFICACIONES**
_Por definir_

**PROTOTIPO MOVIL: CONFIGURACIONES**
_Por definir_

**Comment by lutriana** [comment]
[Prototipo para móvil panel de usuario V.1.pdf](https://github.com/user-attachments/files/17013395/Prototipo.para.movil.panel.de.usuario.V.1.pdf)

**Comment by lutriana** [comment]
Final Version of Web MockUp

![Image](https://github.com/user-attachments/assets/0852a5ac-4ca6-41dd-a3c3-86f6e9b7784f)
![Image](https://github.com/user-attachments/assets/33b51074-dbe6-4fe7-960f-b85d49a21bae)
![Image](https://github.com/user-attachments/assets/fbf49a22-38be-4b93-a52d-5992f44a898e)
![Image](https://github.com/user-attachments/assets/276aa56f-fdcc-4c4b-aa41-564c28e1d029)
![Image](https://github.com/user-attachments/assets/9756c42d-524c-489d-a269-41af47fc336b)
