### ISSUE TITLE
2.1. Configuración del entorno de desarrollo

### ISSUE THREAD

**Issue by sajkcaz19** [ISCOUTB/AH-TaskManager#8]

**Comment by lutriana** [comment]
Para desarrollar nuestro proyecto utilizaremos Visual Studio, Python, Flask y MySQL, las cuales son herramientas claves para desarrollar un gestor de tareas eficiente y escalable, y su integración ofrece varias ventajas:

Visual Studio: Es un entorno de desarrollo integrado (IDE) que facilita la creación, depuración y mantenimiento del código. Con su soporte para múltiples lenguajes y complementos, es ideal para desarrollar aplicaciones web usando Python y Flask, mejorando la productividad y permitiendo un desarrollo más ágil.

Python: Es un lenguaje de programación flexible y sencillo que permite escribir código claro y eficiente. Su extensa biblioteca de paquetes y herramientas lo hace perfecto para desarrollar aplicaciones de backend y lógica de negocio, como un gestor de tareas.

Flask: Es un framework web ligero basado en Python que permite crear aplicaciones web rápidamente. Para un gestor de tareas, Flask proporciona una estructura simple pero potente para manejar rutas, manejar solicitudes de usuario, formularios y trabajar con plantillas para la interfaz de usuario.

MySQL: Es un sistema de gestión de bases de datos relacional que permite almacenar y gestionar grandes volúmenes de datos. Al ser un gestor de tareas, es crucial tener una base de datos para manejar usuarios, tareas, fechas de vencimiento, y otros metadatos. MySQL asegura que los datos se mantengan organizados y accesibles.

En conjunto, estas herramientas proporcionan un entorno robusto y flexible para desarrollar un gestor de tareas eficiente, escalable y fácil de mantener.
